export const skillOptions = [
  "Graphic Designing",
  "UI/UX",
  "Fullstack Development",
  "Backend Development",
  "Frontend Development",
  "Photoshop",
  "React",
  "Node.js",
  "MongoDB",
  "Python",
  "JavaScript",
  "TypeScript",
  "Figma",
  "Video Editing",
  "Content Writing",
  "Data Analysis",
  "AWS",
  "Machine Learning",
  "Artificial Intelligence",
  "Data Science",
  "Blockchain",
  "Cybersecurity",
  "DevOps",
  "Docker",
  "Kubernetes",
  "Cloud Computing",
  "Azure",
  "Google Cloud Platform",
  "SQL",
  "NoSQL",
  "PostgreSQL",
  "MySQL",
  "GraphQL",
  "REST APIs",
  "Java",
  "C++",
  "C#",
  "Ruby on Rails",
  "PHP",
  "Laravel",
  "Swift",
  "Kotlin",
  "Android Development",
  "iOS Development",
  "React Native",
  "Flutter",
  "Digital Marketing",
  "SEO",
  "Social Media Marketing",
  "Copywriting",
  "Project Management",
  "Agile Methodologies",
  "Scrum",
  "Product Management",
  "Business Analysis",
  "Sales",
  "Customer Support",
  "Public Speaking",
  "Leadership",
  "Team Management",
  "Illustration",
  "3D Modeling",
  "Animation",
  "Motion Graphics",
  "Photography",
  "Music Production",
  "Audio Editing",
  "Language Translation",
  "Premiere Pro",
  "After Effects",
  "DaVinci Resolve",
  "Color Grading",
  "VFX",
  "Sound Design",
  "Accounting",
  "Finance",
  "Economics",
  "Tally",
  "Taxation",
  "Business Law",
  "Auditing",
  "Genetics",
  "Microbiology",
  "Anatomy",
  "Zoology",
  "Botany",
  "Bioinformatics",
  "Cell Biology",
  "Data Structures",
  "Algorithms",
  "Operating Systems",
  "Computer Networks",
  "DBMS",
  "System Design",
  "Software Engineering",
  "Go",
  "Calculus",
  "Linear Algebra",
  "Statistics",
  "Probability",
  "Discrete Mathematics",
  "Operations Research",
  "Number Theory",
  "Differential Equations",
];
